services:
  solacheck:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solacheck
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solacheck.rule=Host(`nofey.de`) && PathPrefix(`/solacheck`)"
      - "traefik.http.routers.solacheck.entrypoints=websecure"
      - "traefik.http.routers.solacheck.tls.certresolver=letsencrypt"
      - "traefik.http.services.solacheck.loadbalancer.server.port=3000"
    networks:
      - traefik-net
    environment:
      - NODE_ENV=production

networks:
  traefik-net:
    external: true
