version: '3.8'

services:
  solacheck:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solacheck
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solacheck.rule=Host(`nofey.de`) && PathPrefix(`/solacheck`)"
      - "traefik.http.routers.solacheck.entrypoints=websecure"
      - "traefik.http.routers.solacheck.tls.certresolver=letsencrypt"
      - "traefik.http.services.solacheck.loadbalancer.server.port=3000"
      - "traefik.docker.network=homepage_default"
    networks:
      - homepage_default
    environment:
      - NODE_ENV=production

networks:
  homepage_default:
    name: homepage_default
    external: true
